#!/bin/bash

NS=${PKEBS_NS:-pkbs}

errr() {
	local message=$1

	echo "Error: $message" >&2
	exit 1
}

usage() {
	echo "Usage: qstat [OPTIONS] [[<job ID> | <destination>] ...]"
	echo "Options are as follows"
	echo "    -h    show help"
	exit 1
}

qstat() {
	local arg=$1

	kubectl -n $NS exec dispatcher -- /usr/src/app/qstat.py $arg || errr "qstat failed"
}

while getopts "h" opt; do
    case $opt in
        h)
            usage
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            usage
            ;;
    esac
done

shift $((OPTIND-1))

qstat "$1"

exit $?
