#!/bin/bash

NS=${PKEBS_NS:-pkbs}

opt_a="${WEBDAV_HOSTNAME}"
opt_c=""
opt_F=""
opt_f=""
opt_i="${WEBDAV_INSECURE:-0}"
opt_l="${WEBDAV_LOGIN}"
opt_N=""
opt_P="${WEBDAV_PASSWORD}"
opt_p="${WEBDAV_PATH}"
opt_r="${WEBDAV_ROOT}"
opt_u="${WEBDAV_UPLOAD}"

errr() {
	local message=$1

	echo "Error: $message" >&2
	exit 1
}

usage() {
	echo "Usage: qsub [OPTIONS] [PAYLOAD]"
	echo "If payload is not given, commands are read from the standard input."
	echo "Options are as follows"
	echo "    -a    WebDAV server address (WEBDAV_HOSTNAME)"
	echo "    -f    fixed upload path"
	echo "    -h    show help"
	echo "    -l    username (WEBDAV_LOGIN)"
	echo "    -N    name the job"
	echo "    -q    queue (i.e., namespace)"
	echo "    -P    password (WEBDAV_PASSWORD)"
	echo "    -p    upload path prefix"
	echo "    -r    root (WEBDAV_ROOT)"
	echo "    -u    what to upload, one of files, zip or none (WEBDAV_UPLOAD)"
	exit 1
}

submit_job() {
	local src=$1
	local dst=$2
 	local bytes=$(stat -c %s $src)
	local options=""

	[ -z "$opt_a" ] || options="$options -a $opt_a"
	[ -z "$opt_c" ] || options="$options -c $opt_c"
	[ -z "$opt_f" ] || options="$options -f $opt_f"
	[ "1" = "$opt_i" ] && options="$options --insecure"
	[ -z "$opt_l" ] || options="$options -l $opt_l"
	[ -z "$opt_N" ] || options="$options -N $opt_N"
	[ -z "$opt_p" ] || options="$options -p $opt_p"
	[ -z "$opt_P" ] || options="$options -P $opt_P"
	[ -z "$opt_r" ] || options="$options -r $opt_r"
	[ -z "$opt_u" ] || options="$options -u $opt_u"

	# NATS message payload by default is up to 1 MB
	[ 1000000 -lt $bytes ] && errr "File $src is too large: $bytes bytes"

	kubectl -n $NS cp $src dispatcher:${dst} || errr "File transfer failed"
	kubectl -n $NS exec dispatcher -- /usr/src/app/dispatcher.py --syslog $options $dst || errr "Dispatch failed"
	unlink $src
}

qsub() {
	local src=$1
	local dst="$(mktemp -u -t qsub-XXXXXXXXXX).zip"

	if [ -f "$src" ] ; then
		[ -x "$src" ] || errr "File $src is not executable"
		zip -j -9 -q $dst $src || errr "Creating zip file failed"
		opt_c=$(basename $src)
	elif [ -d "$src" ] ; then
		local runfile=${src}/run.sh
		[ -f $runfile ] || errr "File $runfile not found"
		( cd $src && zip -9 -q -r $dst . ) || errr "Creating zip file failed"
	else
		errr "Unsupported payload type: $src"
	fi

	submit_job $dst $dst
}

while getopts "a:f:F:hiN:n:P:p:r:q:U:u:" opt; do
    case $opt in
		a)
			opt_a=$OPTARG
            ;;
		F)
			opt_F=$(echo $OPTARG | sed -e 's:[^A-Za-z0-9._/\-]::g' -e 's:^/::' -e 's:/$::')
            ;;
		f)
			opt_f=$(echo $OPTARG | sed -e 's:[^A-Za-z0-9._/\-]::g' -e 's:^/::' -e 's:/$::')
            ;;
        h)
            usage
            ;;
		i)
            opt_i=1
            ;;
        N)
            opt_N=$(echo $OPTARG | sed -e 's:[^A-Za-z0-9._\-]::g')
            ;;
        P)
            opt_P=$OPTARG
            ;;
        p)
            opt_p=$(echo $OPTARG | sed -e 's:[^A-Za-z0-9._/\-]::g' -e 's:^/::' -e 's:/$::')
            ;;
		r)
            opt_r=$(echo $OPTARG | sed -e 's:[^A-Za-z0-9._/\-]::g' -e 's:^/::' -e 's:/$::')
            ;;
		q)
            NS=$(echo $OPTARG | sed -e 's:[^A-Za-z0-9._\-]::g')
            ;;
		U)
            opt_U=$OPTARG
            ;;
        u)
            opt_u=$(echo $OPTARG | sed -e 's:[^A-Za-z0-9._/\-]::g')
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            usage
            ;;
    esac
done

shift $((OPTIND-1))

if [ 0 -ne $# ] ; then
	qsub "$1"
else
	# read input from stdin
	tmp=$(mktemp -t stdin.XXXXXXX)
	chmod u+x $tmp
	cat <&0 > $tmp
	[ -z "$opt_N" ] && opt_N="STDIN"
	qsub $tmp
	unlink $tmp
fi

exit $?
